version: "3.8"

services: 
  mysql:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./env/db.env
    restart: always

  wordpress:
    build:
      context: ./dockerfiles
      dockerfile: wordpress-php-fpm.dockerfile
    
    volumes:
      - ./wordpress:/var/www/html/
    depends_on:
      - mysql
    env_file:
      - ./env/wordpress.env
    links:
      - mysql
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html/
    ports:
      - 8080:80
    links:
      - "wordpress"
