version: "3.8"

services: 
  mysql:
    build:
      context: .
      dockerfile: ./dockerfiles/mariadb-container.dockerfile
    volumes:
      - ./mysql:/var/lib/mysql
      # - ./mysql:/opt
    env_file:
      - ./env/db.env
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: ./dockerfiles/wordpress-php-fpm.dockerfile
    volumes:
      - ./wordpress:/var/www/html/
    depends_on:
      - mysql
    env_file:
      - ./env/wordpress.env
    links:
      - mysql
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html/
    ports:
       - 8081:80      
    depends_on:
      - mysql
      - wordpress  
    links:
      - "wordpress"
  
volumes:
  mysql:
