---
- hosts: localhost
  connection: local
  become: yes

  tasks:
   - name: Read-write git checkout from github
     git:
      repo: https://github.com/Alex-SBK/wordpress-as-multicontainer.git
      dest: /home/vagrant/app
  
   - name: Deploy multicontainer web application using docker-compose
     shell: 'docker-compose  -p prod -f /home/vagrant/app/wordpress-application/docker-compose.yml --env-file /home/vagrant/app/wordpress-application/docker-compose-env/env.prod  up -d'