---

# Edit lib/systemd/system/docker.service
- name: comment ExecStart line in docker.sercive
  shell: "sed -i 's/^ExecStart/#&/' /lib/systemd/system/docker.service"
# Add new line after comented
- name: add new line
  shell: "sed -i '/^#ExecStart.*/iExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock\n' /lib/systemd/system/docker.service"

- name: Just force systemd to reread configs and reload docker
  systemd:
    daemon_reload: yes 
    state: restarted
    name: docker