---
- hosts: all
  become: yes

  tasks:
    
    - name: Creates directory
      file:
        path: /var/lib/jenkins/workspace/
        state: directory
        owner: jenkins

    - name: Create a symbolic link
      file:
        src: /wordpress-application
        dest: /var/lib/jenkins/workspace/wordpress-application
        state: link

    - name: SET job my-maven-java-project
      shell: "java -jar /opt/jenkins-cli.jar -s http://127.0.0.1:8080/  -auth {{jenkins_admin_username}}:{{jenkins_admin_password}} create-job wordpress-application < /wordpress-application/jenkins-jobs/wordpress-application.xml"
     
     