---
- hosts: all
  become: yes

  tasks:
# tasks file for install Ansible to Debian systems


  - name: Install latest version of ansible"
    apt:
      name: ansible
      state: latest

  - name: Add the user 'jenkins' into docker group
    user:
      name: jenkins
      shell: /bin/bash
      groups: docker
      append: yes    
  
  - name: Unconditionally reboot the machine with all defaults
    reboot:
   